services:
  php:
    env_file:
      - .env.local
    build:
      context: .
      target: frankenphp_prod
    image: noho
    restart: always
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: noho.fr, www.noho.fr
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}

  database:
    restart: always
    ports:
      - "5432"

  rabbitmq:
    restart: always
    ports:
      - "15672"

volumes:
  caddy_data:
  caddy_config:
